---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  create KMS Keys the project ASA
  Last Modified: 10 September 2021
  Author: Exec <aerioeus@gmail.com>


Metadata: {}
Mappings: {}
Conditions: {}

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_WEATHER

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME


Resources:

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Key to encrypt/ decrypt ssm in ASA project"
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          -
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/Exec
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal:
              AWS:
                # - !Sub arn:aws:iam::${AWS::AccountId}:user/username
                - !Sub arn:aws:iam::${AWS::AccountId}:user/Exec
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
      Tags:
        - Key: Name
          Value: Openweather CMK

Outputs:

  StackName:
    Description: the Stackname
    Value: !Ref AWS::StackName

  KMSKey:
    Description: The ARN of the creates KMS-Key
    Value: Fn::GetAtt [KMSKey, Arn]
    Export:
      Name: !Sub ${Project}-KMSKey-CMK