AWSTemplateFormatVersion: 2010-09-09
Description: >
  creates secure parameter for the Project WeatherAppKey
  Last Modified: 11.09.2021
  Author: Exec <aerioeus@gmail.com>

Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_WEATHER

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME


Resources:
  # API Key Openweather
  OpenweatherAPIKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: OpenWeather_API_Key
      KmsKeyId:
        Fn::ImportValue: !Sub ${Project}-KMSKey-CMK
      Name: OpenWeather_API_Key
      SecretString: 621955404ba1a42a516e426c1cb13635
      Tags:
        - Key: AppName
          Value: AppB

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  OpenweatherAPIName:
    Description: The ARN of the Secret
    Value: !Ref OpenweatherAPIKey
    Export:
      Name: !Sub ${EnvironmentName}-OpenweatherAPI-Arn