AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates template for creating a Hosted Zone in Route53
  Last Modified: 14.04.2022
  Author: Exec <aerioeus@gmail.com>

Metadata: {}

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/GLOBAL

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  ApexDomainName1:
    Type: String
    Description: DNS name of a Route 53 Public hosted zone
    Default: energicos.info

  CloudfrontEndpoint:
    Description: Amazon CloudFront distributions has one single endpoint
    Type: String
    Default: cloudfront.amazonaws.com

  CloudfrontHostedZoneId:
    Description: Amazon CloudFront distributions has one HostedZoneId
    Type: String
    Default: Z2FDTNDATAQYW2


Mappings:
  RegionMap:
    us-east-1:
      S3HostedZoneId: Z3AQBSTGFYJSTF
      S3WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
    us-east-2:
      S3HostedZoneId: Z2O1EMRO9K5GLX
      S3WebsiteEndpoint: s3-website-us-east-2.amazonaws.com
    us-west-1:
      S3HostedZoneId: Z2F56UZL2M1ACD
      S3WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3HostedZoneId: Z3BJ6K6RIION7M
      S3WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3HostedZoneId: Z1BKCTXD74EZPE
      S3WebsiteEndpoint: s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      S3HostedZoneId: Z3GKZC51ZF0DB4
      S3WebsiteEndpoint: s3-website-eu-west-2.amazonaws.com
    eu-west-3:
      S3HostedZoneId: Z3R1K369G5AVDG
      S3WebsiteEndpoint: s3-website-eu-west-3.amazonaws.com
    eu-central-1:
      S3HostedZoneId: Z21DNDUVLTQW6Q
      S3WebsiteEndpoint: s3-website-eu-central-1.amazonaws.com


Resources:
  HostedZonePublic1:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join ['', ['Hosted zone for ', !Ref 'ApexDomainName1', !Sub ' for ${Project}' ]]
      Name: !Ref ApexDomainName1
#      QueryLoggingConfig:
#        CloudWatchLogsLogGroupArn: !GetAtt Route531LogGroup.Arn
      HostedZoneTags:
      - Key: EBS
        Value: homepage

Outputs:
  StackName:
    Description: returns the Stack Name
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  Subproject:
    Description: The project name
    Value: !Ref Subproject

  HostedZonePublic1:
    Description: returns the hosted zone ID
    Value: !Ref HostedZonePublic1
    Export:
      Name: !Sub ${Project}-HostedZonePublic1

  # this one only works for public hosted zones
#  NameServerHostedZone1:
#    Description: returns the hosted zone nameservers as a list
#    Value: !GetAtt HostedZonePublic1.NameServers
#    Export:
#      Name: !Sub ${EnvironmentName}-${Project}-NameServersHostedZonePublic1
