---
AWSTemplateFormatVersion: 2010-09-09
Description: >
 create sns topics for the project invoicegenerator
 Last Modified: 10 September 2018
 Author: Exec <aerioeus@gmail.com>

Metadata: {}
Mappings: {}
Conditions: {}


Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_WEATHER

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  EmailEndPoint1:
    Type: String
    Description: The endpoint that receives notifications from the Amazon SNS topic.
      The endpoint value depends on the protocol that you specify. This could be a
      URL or ARN
    Default: awssns@energicos.com

  EmailEndPoint2:
    Type: String
    Description: The endpoint that receives notifications from the Amazon SNS topic.
      The endpoint value depends on the protocol that you specify. This could be a
      URL or ARN
    Default: cloudtrailmetrics@energicos.com

  SubscriptionProtocol1:
    Type: String
    Description: The subscription's protocol
    AllowedValues:
    - http
    - https
    - email
    - email-json
    - sms
    - sqs
    - application
    - lambda
    Default: email

  SubscriptionProtocol2:
    Type: String
    Description: The subscription's protocol
    AllowedValues:
    - http
    - https
    - email
    - email-json
    - sms
    - sqs
    - application
    - lambda
    Default: email

  # Alarmparameter
  AlarmthresholdSNS1:
    Description: Treshold for number of messages that Amazon SNS failed to deliver
    Type: String
    Default: '1'

Resources:
  # CodeCommit Notifications
  CodeCommitTopic:
    Type: AWS::SNS::Topic
    Properties: {}

  CodeCommitTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailEndPoint1
      Protocol: !Ref SubscriptionProtocol1
      TopicArn: !Ref CodeCommitTopic

  # Billing Notifications
  BillingTopic:
    Type: AWS::SNS::Topic
    Properties: {}

  BillingTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailEndPoint1
      Protocol: !Ref SubscriptionProtocol1
      TopicArn: !Ref BillingTopic

  # Cloudtrail Notifications
  TrailTopic:
    Type: AWS::SNS::Topic
    Properties: {}

  TrailTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailEndPoint1
      Protocol: !Ref SubscriptionProtocol1
      TopicArn: !Ref TrailTopic

  TrailTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailSNSPolicy
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource: !Ref TrailTopic
          Action: 'sns:Publish'
      Topics:
      - !Ref TrailTopic

  # Alarmtopic
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        -
          Endpoint: !Ref EmailEndPoint1
          Protocol: !Ref SubscriptionProtocol1

  # Codebuild Notifications
  CodebuildTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        -
          Endpoint: !Ref EmailEndPoint1
          Protocol: !Ref SubscriptionProtocol1

  # Codepipeline Notifications
  CodepipelineTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        -
          Endpoint: !Ref EmailEndPoint1
          Protocol: !Ref SubscriptionProtocol1

  # ALARMS
  # Alarm NumberOfNotificationsFailed
  BillingNumberOfNotificationsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: monitors number of messages that Amazon SNS failed to deliver
      Namespace: AWS/SNS
      MetricName: NumberOfNotificationsFailed
      Dimensions:
      - Name: TopicName
        Value: !GetAtt BillingTopic.TopicName
      Statistic: Sum
      Period: 360
      EvaluationPeriods: 1
      Threshold: !Ref AlarmthresholdSNS1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - !Ref BillingTopic
      InsufficientDataActions:
      - !Ref BillingTopic
      OKActions:
      - !Ref BillingTopic
      TreatMissingData:  notBreaching

  CodeCommitNumberOfNotificationsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: monitors number of messages that Amazon SNS failed to deliver
      Namespace: AWS/SNS
      MetricName: NumberOfNotificationsFailed
      Dimensions:
      - Name: TopicName
        Value: !GetAtt CodeCommitTopic.TopicName
      Statistic: Sum
      Period: 360
      EvaluationPeriods: 1
      Threshold: !Ref AlarmthresholdSNS1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - !Ref CodeCommitTopic
      InsufficientDataActions:
      - !Ref CodeCommitTopic
      OKActions:
      - !Ref CodeCommitTopic
      TreatMissingData:  notBreaching

  AlarmNumberOfNotificationsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: monitors number of messages that Amazon SNS failed to deliver
      Namespace: AWS/SNS
      MetricName: NumberOfNotificationsFailed
      Dimensions:
      - Name: TopicName
        Value: !GetAtt AlarmTopic.TopicName
      Statistic: Sum
      Period: 360
      EvaluationPeriods: 1
      Threshold: !Ref AlarmthresholdSNS1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - !Ref AlarmTopic
      InsufficientDataActions:
      - !Ref AlarmTopic
      OKActions:
      - !Ref AlarmTopic
      TreatMissingData:  notBreaching

  CodebuildNumberOfNotificationsFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: monitors number of messages that Amazon SNS failed to deliver
      Namespace: AWS/SNS
      MetricName: NumberOfNotificationsFailed
      Dimensions:
      - Name: TopicName
        Value: !GetAtt CodebuildTopic.TopicName
      Statistic: Sum
      Period: 360
      EvaluationPeriods: 1
      Threshold: !Ref AlarmthresholdSNS1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - !Ref CodebuildTopic
      InsufficientDataActions:
      - !Ref CodebuildTopic
      OKActions:
      - !Ref CodebuildTopic
      TreatMissingData:  notBreaching

Outputs:
  # TopicARNs
  CodeCommitTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref CodeCommitTopic
    Export:
      Name: !Sub ${Project}-CodeCommitTopicARN

  BillingTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref BillingTopic
    Export:
      Name: !Sub ${Project}-BillingTopicARN

  TrailTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref TrailTopic
    Export:
      Name: !Sub ${Project}-TrailTopicARN

  AlarmTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub ${Project}-AlarmTopicARN

  CodebuildTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref CodebuildTopic
    Export:
      Name: !Sub ${Project}-CodebuildTopicARN

  CodepipelineTopicARN:
    Description: ARN of newly created SNS Topic
    Value: !Ref CodepipelineTopic
    Export:
      Name: !Sub ${Project}-CodepipelineTopicARN

  # TopicName
  CodeCommitTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt CodeCommitTopic.TopicName
    Export:
      Name: !Sub ${Project}-CodeCommitTopicName

  BillingTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt BillingTopic.TopicName
    Export:
      Name: !Sub ${Project}-BillingTopicName

  TrailTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt TrailTopic.TopicName
    Export:
      Name: !Sub ${Project}-TrailTopicName

  AlarmTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt AlarmTopic.TopicName
    Export:
      Name: !Sub ${Project}-AlarmTopicName

  CodebuildTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt CodebuildTopic.TopicName
    Export:
      Name: !Sub ${Project}-CodebuildTopicName

  CodepipelineTopicName:
    Description: Name of newly created SNS Topic
    Value: !GetAtt CodepipelineTopic.TopicName
    Export:
      Name: !Sub ${Project}-CodepipelineTopicName