AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates a lambda function to pull data from a weather API
  Last Modified: 17.09.2021
  Author: Exec <aerioeus@gmail.com>

Metadata: {}

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_WEATHER

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

Resources:
  dataprocessingLayer:
    Type: AWS::Lambda::LayerVersion
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      Content:
        S3Bucket:
          Fn::ImportValue: !Sub '${Project}-LayerCode-Name'
        S3Key: layers/dp-layer.zip
      Description: a dataprocessing layer
      LayerName: dataprocessinglayer
      LicenseInfo: MIT


  dataprocessingLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref dataprocessingLayer
      Principal: !Ref AWS::AccountId


Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  dataprocessingLayerArn:
    Description: Amazon Resource Name (ARN) of the dataprocessingLayer
    Value: !Ref dataprocessingLayer
    Export:
      Name: !Sub ${Project}-${Subproject}-dataprocessingLayerARN