AWSTemplateFormatVersion: 2010-09-09
Description:  >
  Backup Plan template for thin backups
  Last Modified: 06.10.2021
  Author: Exec <aerioeus@gmail.com>

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/GLOBAL

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  Retention1:
    Description: Enter the number of days to keep the backups. must be greater than 1
    Type: Number
    Default: 30
    MinValue: 7
    MaxValue: 30
    ConstraintDescription: must be between 7 and 30

  Retention2:
    Description: Enter the number of days to keep the backups. must be greater than 1
    Type: Number
    Default: 180
    MinValue: 60
    MaxValue: 360
    ConstraintDescription: must be between 60 and 360

  Retention3:
    Description: Enter the number of days to keep the backups. must be greater than 1
    Type: Number
    Default: 360
    MinValue: 360
    MaxValue: 720
    ConstraintDescription: must be between 360 and 720

  CronExpression1:
    Description: the cron expression for your backup plan ; is triggered every day at 5:00 am UTC
    Type: String
    Default: "cron(0 5 ? * * *)"

  CronExpression2:
    Description: Enter the cron expression for your backup plan; Run at 11:00 pm (UTC) every Monday
    Type: String
    Default: "cron(0 23 ? * 2 *)"

  CronExpression3:
    Description: >
      cron expression for your backup plan;
      triggered at 10:15am UTC on the last Friday of each month during the years 2021 to 2023
    Type: String
    Default: "cron(15 10 ? * 6L 20021-2023)"


Resources:
  Vault1:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: BackupVaultDDB
      EncryptionKeyArn:
        Fn::ImportValue: !Sub ${Project}-KMSKey-CMK

  BackupPlan1:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: BackupPlanWithThinBackups
        BackupPlanRule:
          -
            RuleName: RuleForDailyBackups
            TargetBackupVault: !Ref Vault1
            ScheduleExpression: !Ref CronExpression1
            Lifecycle:
              DeleteAfterDays: !Ref Retention1
          -
            RuleName: RuleForWeeklyBackups
            TargetBackupVault: !Ref Vault1
            ScheduleExpression:  !Ref CronExpression2
            Lifecycle:
              DeleteAfterDays: !Ref Retention2
          -
            RuleName: RuleForMonthlyBackups
            TargetBackupVault: !Ref Vault1
            ScheduleExpression: "cron(0 5 1 * ? *)"
            Lifecycle:
              DeleteAfterDays:  !Ref Retention3
    DependsOn:
      - Vault1

  BackupSelection1:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupSelection:
        SelectionName: TagBasedBackupSelection
        IamRoleArn:
          Fn::ImportValue: !Sub '${Project}-BackupRoleARN'
        ListOfTags:
         -
           ConditionType: STRINGEQUALS
           ConditionKey: backup
           ConditionValue: thinbackup
      BackupPlanId: !Ref BackupPlan1
    DependsOn:
      - BackupPlan1
      - Vault1

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  BackupVaultName:
    Description: The Name of the Backup Vault
    Value: !Ref Vault1
    Export:
      Name: !Sub ${EnvironmentName}-Vault1-Name

  BackupVaultARN:
    Description: The Arn of the Backup Vault
    Value: !GetAtt Vault1.BackupVaultArn
    Export:
      Name: !Sub ${EnvironmentName}-Vault1-Arn

  BackupSelectionName:
    Description: Tag:Value you need to put on your resource along with the Tag:Key Backup
    Value: !Ref BackupSelection1

  BackupSelectionId:
    Description: Backup Selection ID
    Value: !Ref BackupSelection1

  BackupPlanArn:
    Description: BackupPlan Arn
    Value: !GetAtt BackupPlan1.BackupPlanArn

  BackupPlanId:
    Description: BackupPlan ID
    Value: !Ref BackupPlan1

  BackupPlanVersionId:
    Description: BackupPlan Version ID
    Value: !GetAtt BackupPlan1.VersionId