AWSTemplateFormatVersion: 2010-09-09
Description: >
  creates secure and unsecure parameter for the Project WeatherAppKey
  Last Modified: 11.09.2021
  Author: Exec <aerioeus@gmail.com>

Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: The project name
    Type: String
    Default: ASA

  Subproject:
    Description: Enter Project Name
    Type: String
    Default: none

Resources:
  # creates Environment for the lifecycle
  EnvironmentName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/ENVIRONMENT_NAME
      Type: String
      Value: Dev
      Description: An environment name that will be prefixed to resource names

  LeadDeveloper:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/LEAD-DEVELOPER_NAME
      Type: String
      Value: Andreas Rose
      Description: Lead Developer

  ProjectAll:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/GLOBAL
      Type: String
      Value: global
      Description: a project name that will be prefixed to resource names

  Project1:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/PROJECT_WEATHER
      Type: String
      Value: weatherdata
      Description: a project name that will be prefixed to resource names

  Project2:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/PROJECT_IOT
      Type: String
      Value: iot
      Description: a project name that will be prefixed to resource names

  Project3:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/PROJECT_ASA
      Type: String
      Value: asa
      Description: a project name that will be prefixed to resource names

  Table1:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/Table_weatherdata
      Type: String
      Value: hourlyWeatherData
      Description: a table name that will be prefixed to resource names

  Table2:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/Table_iot
      Type: String
      Value: iotData
      Description: a table name that will be prefixed to resource names

  Table3:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/Table_weatherdatahist
      Type: String
      Value: hourlyWeatherDatahistorical
      Description: a table name that will be prefixed to resource names

  CognitoIdentityPool1:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/COGNITOPOOL_iot
      Type: String
      Value: AWSIdentityPool
      Description: a name that will be prefixed to resource names

  # API Key Openweather
  OpenweatherAPI:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: OpenWeather_API_Key
      Type: String
      Value: 621955404ba1a42a516e426c1cb13635
      Description: An environment name that will be prefixed to resource names

  # Bucket Names
  # Bucket Names must all be in small caps
  CFTemplatesBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/CFTemplatesBucket
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-templatescfn'
      Description: a bucket name

  LambdaCodeBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/LambdaCodeBucket
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-lambdacode'
      Description: a bucket name

  WeatherDataBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/WeatherDataBucket
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-weatherdata'
      Description: a bucket name

  WeatherDataBucket2:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/WeatherData
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-weatherdetails'
      Description: a bucket name

  LayerCodeBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/LayerCodeBucket
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-lambdalayers'
      Description: a bucket name

  StepFunctionStatesBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/StepFunctionStatesBucket
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-stepfunctionsbucket'
      Description: a bucket name

  StepFunction1:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: /energicos/weather/StepFunction1
      Type: String
      Value:
        Fn::Join:
        - ''
        - - !Sub '${AWS::AccountId}-'
          - !GetAtt Project3.Value
          - '-BatchOrchestrator'
      Description: a bucket name

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  LeadDeveloperName:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref LeadDeveloper

  Project:
    Description: The project name
    Value: !Ref Project

  # Names
  OpenweatherAPIName:
    Description: The Name of the parameter
    Value: !Ref OpenweatherAPI
    Export:
      Name: !Sub OpenweatherAPI-Name

  Project1Name:
    Description: The Name of the parameter
    Value: !Ref Project1
    Export:
      Name: !Sub Project1-Name

  Project2Name:
    Description: The Name of the parameter
    Value: !Ref Project2
    Export:
      Name: !Sub Project2-Name

  Project3Name:
    Description: The Name of the parameter
    Value: !Ref Project3
    Export:
      Name: !Sub Project3-Name

  Table1IName:
    Description: The Name of the parameter
    Value: !Ref Table1
    Export:
      Name: !Sub Table1-Name

  Table2IName:
    Description: The Name of the parameter
    Value: !Ref Table2
    Export:
      Name: !Sub Table2-Name

  Table3IName:
    Description: The Name of the parameter
    Value: !Ref Table3
    Export:
      Name: !Sub Table3-Name

  CognitoIdentityPool1IName:
    Description: The Name of the parameter
    Value: !Ref CognitoIdentityPool1
    Export:
      Name: !Sub CognitoIdentityPool1-Name

  WeatherDataBucketName1:
    Description: The Name of the parameter
    Value: !Ref WeatherDataBucket1
    Export:
      Name: !Sub WeatherDataBucket1-Name

  WeatherDataBucketName2:
    Description: The Name of the parameter
    Value: !Ref WeatherDataBucket2
    Export:
      Name: !Sub WeatherDataBucket2-Name

  Stepfunction1Name:
    Description: The Value of the parameter
    Value: !Ref StepFunction1
    Export:
      Name: !Sub StepFunction1-Name

  # Values
  OpenweatherAPIValue:
    Description: The Value of the parameter
    Value: !GetAtt OpenweatherAPI.Value
    Export:
      Name: !Sub OpenweatherAPI-Value

  Project1Value:
    Description: The Value of the parameter
    Value: !GetAtt Project1.Value
    Export:
      Name: !Sub Project1-Value

  Project2Value:
    Description: The Value of the parameter
    Value: !GetAtt Project2.Value
    Export:
      Name: !Sub Project2-Value

  Project3Value:
    Description: The Value of the parameter
    Value: !GetAtt Project3.Value
    Export:
      Name: !Sub Project3-Value

  Table1Value:
    Description: The Value of the parameter
    Value: !GetAtt Table1.Value
    Export:
      Name: !Sub Table1-Value

  Table2Value:
    Description: The Value of the parameter
    Value: !GetAtt Table2.Value
    Export:
      Name: !Sub Table2-Value

  Table3Value:
    Description: The Value of the parameter
    Value: !GetAtt Table2.Value
    Export:
      Name: !Sub Table3-Value

  CognitoIdentityPool1Value:
    Description: The Value of the parameter
    Value: !GetAtt CognitoIdentityPool1.Value
    Export:
      Name: !Sub CognitoIdentityPool1-Value

  WeatherDataBucketValue1:
    Description: The Value of the parameter
    Value: !GetAtt WeatherDataBucket1.Value
    Export:
      Name: !Sub WeatherDataBucket1-Value

  WeatherDataBucketValue2:
    Description: The Value of the parameter
    Value: !GetAtt WeatherDataBucket2.Value
    Export:
      Name: !Sub WeatherDataBucket2-Value

  Stepfunction1Value:
    Description: The Value of the parameter
    Value: !GetAtt StepFunction1.Value
    Export:
      Name: !Sub StepFunction1-Value