---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This masterstack-template deploys IAM user, groups, roles and policies
  Note that you will need to specify the CAPABILITY_IAM flag
  when you create the stack to allow this template to execute. You can do this through
  the AWS management console by clicking on the check box acknowledging that you understand
  this template creates IAM resources or by specifying the CAPABILITY_IAM flag to
  the cfn-create-stack command line tool
  Last Modified: 19 September 2021
  Author: Exec <aerioeus@gmail.com>

Parameters:
  Owner:
    Description: Individual Name Responsible for the Stack
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/LEAD-DEVELOPER_NAME

  Project:
    Description: The project name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/PROJECT_ASA

  Subproject:
    Description: Enter Project Name
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/GLOBAL

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/ENVIRONMENT_NAME

  CFTemplatesBucketName:
    Description: Name for a bucket to be used in the ressource
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /energicos/weather/CFTemplatesBucket

Resources:
  Policies:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/iam_policies.yaml
      TimeoutInMinutes: '5'

  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/iam_roles.yaml
      TimeoutInMinutes: '5'
      Parameters:
        ManagedPolicy1:
          Fn::GetAtt:
          - Policies
          - Outputs.CodeBuildServiceRolePolicy
        ManagedPolicy2:
          Fn::GetAtt:
          - Policies
          - Outputs.CloudFormationPolicy
        ManagedPolicy3:
          Fn::GetAtt:
          - Policies
          - Outputs.CodePipelinePolicy
        ManagedPolicy5:
          Fn::GetAtt:
          - Policies
          - Outputs.ReadwriteS3Policy
        ManagedPolicy6:
          Fn::GetAtt:
          - Policies
          - Outputs.CloudWatchPutMetricsRolePolicy
        ManagedPolicy7:
          Fn::GetAtt:
          - Policies
          - Outputs.CloudFormationStacksetAdministrationRolePolicy
        ManagedPolicy8:
          Fn::GetAtt:
          - Policies
          - Outputs.RootPolicy
        ManagedPolicy9:
          Fn::GetAtt:
            - Policies
            - Outputs.LambdaExecutionPolicy
        ManagedPolicy15:
          Fn::GetAtt:
          - Policies
          - Outputs.CodepipelineS3Policy
        ManagedPolicy16:
          Fn::GetAtt:
          - Policies
          - Outputs.CloudTrailDeliverLogsRolePolicy

  UserGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/iam_user_groups.yaml
      TimeoutInMinutes: '5'
      Parameters:
        ReleaseManagerPolicy:
          Fn::GetAtt:
          - Policies
          - Outputs.ReleaseManagerPolicy
        DeveloperPolicy:
          Fn::GetAtt:
          - Policies
          - Outputs.DeveloperPolicy
        TesterPolicy:
          Fn::GetAtt:
          - Policies
          - Outputs.TesterPolicy



Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  # output from nested Roles stack
  StackNameRoles:
    Description: The Name of the Stack Roles
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.StackNameRoles
    Export:
      Name: !Sub ${Project}-StackNameRoles

  RootRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.RootRoleARN
    Export:
      Name: !Sub ${Project}-RootRoleARN

  RootRoleName:
    Description: The Name of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.RootRoleName
    Export:
      Name: !Sub ${Project}-RootRoleName

  CodeBuildRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.CodeBuildRoleARN
    Export:
      Name: !Sub ${Project}-CodeBuildRoleARN

  CloudFormationRoleARN:
    Description: The ARN of the Role
    Value: !
      Fn::GetAtt:
      - Roles
      - Outputs.CloudFormationRoleARN
    Export:
      Name: !Sub ${Project}-CloudFormationRoleARN

  CodePipelineRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.CodePipelineRoleARN
    Export:
      Name: !Sub ${Project}-CodePipelineRoleARN

  AdministrationRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.AdministrationRoleARN
    Export:
      Name: !Sub ${Project}-AdministrationRoleARN

  ExecutionRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.ExecutionRoleARN
    Export:
      Name: !Sub ${Project}-ExecutionRoleARN

  CloudWatchPutMetricsRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.CloudWatchPutMetricsRoleARN
    Export:
      Name: !Sub ${Project}-CloudWatchPutMetricsRoleARN

  CloudTrailLogsRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.CloudTrailLogsRoleARN
    Export:
      Name: !Sub ${Project}-CloudTrailLogsRoleARN

  ApiGatewayRoleARN:
    Description: The ARN of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.ApiGatewayRoleARN
    Export:
      Name: !Sub ${Project}-ApiGatewayRoleARN

  LambdaExecutionRoleARN:
    Description: The ARN of the Role
    Value: !GetAtt Roles.Outputs.LambdaExecutionRoleARN
    Export:
      Name: !Sub ${Project}-LambdaExecutionRoleARN

  BackupRoleARN:
    Description: The ARN of the Role
    Value: !GetAtt Roles.Outputs.BackupRoleARN
    Export:
      Name: !Sub ${Project}-BackupRoleARN

  # RoleNames
  CloudWatchPutMetricsRoleName:
    Description: The Name of the Role
    Value:
      Fn::GetAtt:
      - Roles
      - Outputs.CloudWatchPutMetricsRoleName
    Export:
      Name: !Sub ${Project}-CloudWatchPutMetricsRoleName

  ApiGatewayRoleName:
    Description: The Name of the Role
    Value: !GetAtt Roles.Outputs.ApiGatewayRoleName
    Export:
      Name: !Sub ${Project}-ApiGatewayRoleName

  LambdaExecutionRoleName:
    Description: The Name of the Role
    Value: !GetAtt Roles.Outputs.LambdaExecutionRoleName
    Export:
      Name: !Sub ${Project}-LambdaExecutionRoleName

  BackupRoleName:
    Description: The Name of the Role
    Value: !GetAtt Roles.Outputs.BackupRoleName
    Export:
      Name: !Sub ${Project}-BackupRoleName

# output from nested User Group stack
  StackNameUserGroups:
    Description: The Name of the Stack UserGroups
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.StackNameUserGroups
    Export:
      Name: !Sub ${Project}-StackNameUserGroups

  ReleaseMngrAccessKey:
    Description: AWSAccessKeyId of new user Release Manager
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.ReleaseMngrAccessKey
    Export:
      Name: !Sub ${Project}-ReleaseMngrAccessKey

  ReleaseMngrSecretKey:
    Description: AWSSecretKey of new user Release Manager
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.ReleaseMngrSecretKey
    Export:
      Name: !Sub ${Project}-ReleaseMngrSecretKey

  DevAccessKey:
    Description: AWSAccessKeyId of new user Developer
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.DevAccessKey
    Export:
      Name: !Sub ${Project}-DevAccessKey

  DevSecretKey:
    Description: AWSSecretKey of new user Developer
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.DevSecretKey
    Export:
      Name: !Sub ${Project}-DevSecretKey

  TesterAccessKey:
    Description: AWSAccessKeyId of new user Tester
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.TesterAccessKey
    Export:
      Name: !Sub ${Project}-TesterAccessKey

  TesterSecretKey:
    Description: AWSSecretKey of new user Tester
    Value:
      Fn::GetAtt:
      - UserGroups
      - Outputs.TesterSecretKey
    Export:
      Name: !Sub ${Project}-TesterSecretKey


